DATA1			SEGMENT
COUNT		DW	  	20
SADDR		DB    	1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
DAADR		DB		20  DUP(?)
DATA1			ENDS

CODE1		SEGMENT
				ASSUME	CS:CODE1, DS:DATA1
DMOV			PROC	FAR
				PUSH	DS			;
				MOV		AX, 0		;
				PUSH	AX			;
				MOV		AX, DATA1
				MOV		DS, AX
				MOV		SI, OFFSET	SADDR
				MOV		DI, OFFSET	DAADR
				MOV		CX, COUNT
NEXTMOV:		MOV		AL, [SI]
				MOV		[DI], AL
				INC		SI
				INC		DI
				DEC		CX
				JNZ		NEXTMOV
DONE:			RET					;
DMOV			ENDP
CODE1			ENDS
				END	DMOV

